### PR TITLE
feat(procfile): add support to test dockerfile app with proctype WEB

### PR DESCRIPTION
**Pull request by smothiki**
fixes https://github.com/deis/workflow-e2e/issues/208

### CODE REVIEW

**Comment by mboersma** [comment]
This looks great @smothiki. My only concern is that these test specs are part of the default `SKIP_TEST` regex, so they aren't run in e2e, just manually on-demand. (We still need to implement a nightly job for "all buildpacks|dockerfiles.")

I think covering the dockerfile + buildpack case should be included in CI runs for each PR, because controller changes could break this complicated behavior. Maybe we could move this test to a different go file, or tweak the regex so that this is run by default?

**Comment by smothiki** [comment]
I'm leaving the changes in the dockerfile tests as it is. Modified git push tests

**Comment by mboersma** [comment]
> Modified git push tests

That should cover it until we figure out how/when we want to run the skipped specs. Thanks!

**Comment by helgi** [comment]
Remember to update the `deployment_` duplicates with the same changes

**Pull request merged**
