### PR TITLE
feat(dns): change xip to nip

### PR DESCRIPTION
**Pull request by smothiki**
http://nip.io/
uses power DNS backend hopefully solves dns failures

### CODE REVIEW

**Comment by smothiki** [comment]
@vdice @kmala @helgi PTAL

**Comment by helgi** [comment]
Can you change the comment as well

**Comment by sgoings** [comment]
There will be associated changes in https://github.com/sgoings/chart-mate as well.

**Comment by vdice** [comment]
change has been made in chart-mate https://github.com/sgoings/chart-mate/pull/36

**Pull request merged**
