### PR TITLE
feat(limits-cmd): accept new limits:set value type

### PR DESCRIPTION
**Pull request by zinuzoid**
Accept new cli format limits:set web=500m/2000m
Value is map to requests/limits parameter in Kubernetes resource management.
See https://github.com/deis/workflow/issues/562

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by kmala** [comment]
Jenkins, Add to whitelist.

**Comment by mboersma** [comment]
Jenkins, test this please.

**Comment by vdice** [comment]
@zinuzoid It looks like the added e2e specs still need some work to pass CI; see https://ci.deis.io/job/workflow-chart-e2e/235/console

**Comment by bacongobbler** [comment]
ping @zinuzoid ^^

**Comment by zinuzoid** [comment]
Hmm, I cannot see the console @vdice 

```
HTTP ERROR 404
Problem accessing /job/workflow-chart-e2e/235/
```

**Comment by zinuzoid** [comment]
I did a rebase. seems pass now.

**Comment by bacongobbler** [comment]
very nice. 👍

**Comment by vdice** [comment]
@zinuzoid indeed, looks great!  Thanks once again for the contribution!

**Pull request merged**
