### PR TITLE
fix(auth): update to new missing config error message

### PR DESCRIPTION
**Pull request by Joshua-Anderson**
Requires deis/workflow-cli#169

### CODE REVIEW

**Comment by Joshua-Anderson** [comment]
This is failing CI (the status is wrong) because it doesn't seem to be using the requires syntax

**Comment by bacongobbler** [comment]
@Joshua-Anderson you forgot to add `deis/` to the front of `workflow-cli`. I edited your original comment to demonstrate the correct syntax. :)

**Comment by Joshua-Anderson** [comment]
@bacongobbler It does not use the deis prefix: https://deis.com/docs/workflow/contributing/submitting-a-pull-request/#cross-repo-commits

Note that jenkins only reads from the git commit body anyway, so editing the PR body has no effect.

I personally like the prefix better though, cause then GH auto-links it to the PR.

**Comment by Joshua-Anderson** [comment]
My changes to the help menu broke the e2e `deis help` tests, so I deleted the tests. However, I intend to reimplement the tests in my functional tests soon. Is that ok with everyone? Should I unset the LGTMs to get this re-reviewed?

**Comment by mboersma** [comment]
> Is that ok with everyone?

I think that's fine so long as there's a GitHub issue tracking the intent to re-implement the help tests. My LGTM stands and @vdice or someone else can re-review.

**Comment by Joshua-Anderson** [comment]
> I think that's fine so long as there's a GitHub issue tracking the intent to re-implement the help tests
I opened deis/workflow-cli#182

**Pull request merged**
