### PR TITLE
ref(Dockerfile): don't use alpine, it has known DNS issues

### PR DESCRIPTION
**Pull request by Joshua-Anderson**
cc @jchauncey @helgi

### CODE REVIEW

**Comment by helgi** [comment]
What is the golang image based on?

**Comment by bacongobbler** [comment]
Alpine. Check the tag ;)

> FROM golang:1.6-alpine

**Comment by Joshua-Anderson** [comment]
Nope @helgi: `golang:1.7`, debian jessie

**Comment by bacongobbler** [comment]
if you're referring to go-dev: https://github.com/deis/docker-go-dev/blob/master/rootfs/Dockerfile

**Comment by bacongobbler** [comment]
@Joshua-Anderson sorry, I thought @helgi was referring to the old golang image, not go-dev.

**Comment by Joshua-Anderson** [comment]
This change seems to have broken `git remote` tests in some mysterious way (exit code 129). However, they are going to be implemented in the cli very soon regardless. Is it okay to remove these tests for now?

This did uncover that I am not properly logging the `STDERR` from git when weird errors like this come up, so I plan to fix that as well.

**Pull request merged**
